### ISSUE TITLE
Other page format and QR code with TAB

### ISSUE THREAD

**Issue by verydullabc** [DrMikeyS/COVIDVaccinePatientSlips#7]
Hi. Is it possible/easy to get the QR codes out of this for us to do our own "mail merge" in Word to suit our own labels? 

Also (and I appreciate this is similar to existing "single QR code" thread) would it please be possible to get a single QR with both DOB and NHSno, but with a TAB between them? This would enable our team to more easily work with a single scan, without the need for Powershell...

Thanks in advance!

**Comment by DrMikeyS** [comment]
Thanks for getting in touch.

The tab between thing is very easy, the problem is I cannot find a way to make the tab be recognised correctly by the barcode scanners. What they end up doing is putting a tab in the text field, so you have DOB-tab-NHSno in the DOB box. If anyone can figure this out happy to change it. In the meantime, if you check the manual of your scanner, you can normally set it to put a tab after each scan, which works wonders for us.

The "mail merge" thing is tricky. What exactly are you looking for label-wise?

**Comment by verydullabc** [comment]
Thanks for the reply... and the pointers. Very helpful :) 

I've got a developer friend who's intrigued by the tab issue and going to look into it a bit more for all of us. Will report back here if they get anywhere.

Mail Merge perhaps not the right way to think about this; just exploring options. In a burst of early efficiency, we bought quite a lot of packs of the labels we were already using and I was musing out loud for easy ways to "reformat" your output. 

Will report back on barcodes soon. Thanks again!

**Comment by DrMikeyS** [comment]
To tweak it for different stickers it is a case of trial and error editing the code at the bottom of this file:
https://github.com/DrMikeyS/COVIDVaccinePatientSlips/blob/main/scripts/style.css

It is relatively self explanatory.

The only reason this size sticker was chosen is that it was in the cupboard when I made it.

**Comment by verydullabc** [comment]
Thanks again for your earlier replies and help with this.

My friend has found a fix for the TAB issue and we’ve road tested an adapted version of your code… but I’ve copied him to this email – he’d love to share the insight with you for your own version, or to help in any way he can.

We’re also sorted for our label size now, thanks :)


--
Tim Nash
Vaccine Centre Coordinator

Alliance for Better Care Ltd
| abcltd.org.uk<http://abcltd.org.uk/> | Twitter<https://twitter.com/AllianceBetter>

[lxEeGce3YQb+D8261bH1NJh4AAAAAElFTkSuQmCC]
